# Configuration file for pre-commit (https://pre-commit.com/).
# Please run `pre-commit run --all-files` when adding or changing entries.

repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: []
        types_or: [jupyter, markdown, python, shell]
  
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff
      - id: ruff-format
        args: [--diff]
