export const content = {
  pinglish: {
    announcement: "Ersal رایگان baraye sefaresh-haye balaye €50 arzesh rooz",
    nav: {
      newIn: "New edit",
      collections: "Collections",
      shop: "Shop",
      owner: "Owner",
      developer: "Developer",
      assist: "Assist",
    },
    hero: {
      eyebrow: "Mouher Studio",
      title: "Mouher\nWhat you wear",
      description:
        "Modern clothing for daily movement, built as a commerce storefront with Medusa catalog, cart and checkout foundations.",
      button: "Shop collection",
    },
    products: {
      eyebrow: "Live catalog",
      title: "New arrivals",
      shopAll: "All products",
      empty: "No products match this search.",
      sourceDemo: "Demo catalog",
      sourceLive: "Mouher.com products",
      sourceMedusa: "Medusa catalog",
      loading: "Loading catalog",
      viewLive: "View live product",
    },
    productPage: {
      back: "Back to shop",
      details: "Product details",
      category: "Category",
      collection: "Edit",
      sizes: "Sizes",
      colors: "Colors",
      stock: "Stock",
      related: "Related products",
      openLive: "Open on mouher.com",
      loading: "Loading product",
      notFoundTitle: "Product not found",
      notFoundDescription: "This product is not available in the current catalog snapshot.",
    },
    dashboard: {
      ownerEyebrow: "Owner dashboard",
      ownerTitle: "Business overview",
      ownerDescription:
        "Current catalog, stock, category and merchandising signals from the Mouher products snapshot.",
      assistEyebrow: "Website assist",
      assistTitle: "Client support desk",
      assistDescription:
        "Fast product answers, storefront checks and content tasks for the website assistant.",
      viewStore: "View store",
      websiteAssist: "Website assist",
      owner: "Owner dashboard",
      products: "Products",
      inventory: "Inventory",
      inStock: "In stock",
      lowStock: "Low stock",
      sale: "Sale",
      inventoryValue: "Inventory value",
      categoryMix: "Category mix",
      priorityProducts: "Priority products",
      operations: "Operations",
      name: "Product",
      price: "Price",
      status: "Status",
      badge: "Badge",
      action: "Action",
      open: "Open",
      live: "Live",
      ready: "Ready",
      needsApi: "Needs API",
      developerEyebrow: "Developer workspace",
      developerTitle: "Commerce implementation",
      developerDescription:
        "Protected Medusa Admin proxy, Store API checkout, and browser push delivery status.",
      accountEyebrow: "Customer workspace",
      accountTitle: "Profile atelier",
      accountDescription:
        "A private profile landing page for personal details, style notes, photos and loyalty access.",
      apiSurface: "API surface",
      implementationQueue: "Implementation queue",
      medusaDomains: "Medusa domains",
      storefront: "Storefront",
      backend: "Backend",
      protected: "Protected",
      public: "Public",
      browserPush: "Browser push",
      chromeSafari: "Chrome / Safari",
      search: "Search products or client questions",
      suggestedReply: "Suggested reply",
      productMatches: "Product matches",
      contentQueue: "Content queue",
      missingPhoto: "Missing product photo",
      missingColor: "Missing color data",
      missingSize: "Missing size data",
      saleBadge: "Sale badge",
      noTasks: "No urgent website tasks.",
      outOfStock: "Out of stock",
    },
    account: {
      account: "Account",
      greeting: "Hi, Parham",
      orders: "My orders",
      myInfo: "My Info",
      notifications: "Notifications",
      notifyMeList: "Notify Me List",
      giftCards: "Gift Cards",
      helpCenter: "Help Center",
      signOut: "Sign Out",
      wishlist: "Wishlist",
      viewed: "Viewed",
      recommended: "Recommended for you",
      viewAll: "View all",
      shopFaster: "Shop faster with the app",
      help: "Help",
      trackOrder: "Track Order",
      shippingInfo: "Shipping Info",
      returns: "Returns",
      contactUs: "Contact Us",
      company: "Company",
      careers: "Careers",
      about: "About",
      stores: "Stores",
      ambassadorProgram: "Ambassador Program",
      quickLinks: "Quick Links",
      blog: "Blog",
      sizeGuide: "Size Guide",
      sitemap: "Sitemap",
      checkGiftCardBalance: "Check Gift Card Balance",
      loginTitle: "Sign in to your account",
      createTitle: "Create your account",
      loginDescription:
        "Use a private session to manage your profile, orders, wishlist and notifications.",
      createDescription:
        "Create a Mouher account with a strong password before saving personal information.",
      login: "Login",
      createAccount: "Create account",
      switchToCreate: "Create account",
      switchToLogin: "I already have an account",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      confirmPassword: "Confirm password",
      confirmPasswordPlaceholder: "Repeat your password",
      showPassword: "Show",
      hidePassword: "Hide",
      authSecurityNote:
        "Password is validated in the browser and never saved here. Connect this form to HTTPS backend sessions before production.",
      authRequired: "Sign in or create an account to open your dashboard.",
      authErrorRequired: "Email and password are required.",
      authErrorPasswordLength: "Use at least 8 characters.",
      authErrorPasswordMismatch: "Passwords do not match.",
      profileEyebrow: "Personal profile",
      heroTitle: "Create your Mouher profile",
      heroDescription:
        "Add the details that help Mouher remember your fit, style and preferred way to be contacted.",
      profilePhoto: "Profile photo",
      coverPhoto: "Cover photo",
      addPhoto: "Add photo",
      changePhoto: "Change photo",
      gallery: "Photo gallery",
      addGalleryPhoto: "Add picture",
      profileDetails: "Profile details",
      fullName: "Full name",
      fullNamePlaceholder: "Your name",
      email: "Email",
      emailPlaceholder: "you@example.com",
      phone: "Phone",
      phonePlaceholder: "+39 ...",
      city: "City",
      cityPlaceholder: "Milan",
      styleNotes: "Style notes",
      styleNotesPlaceholder: "Preferred fits, colors, sizes and occasions",
      saveProfile: "Save profile",
      savedProfile: "Profile saved in this browser.",
      previewLabel: "Profile preview",
      emptyName: "Your name",
      emptyLocation: "City and contact details",
      emptyBio: "Your fit notes, favorite colors and preferred pieces will appear here.",
      browserPush: "Browser push",
      browserSupported: "Supported in this browser",
      browserUnsupported: "Unavailable in this browser",
      customerId: "Customer ID",
      customerPlaceholder: "cus_...",
      enable: "Enable loyalty notifications",
      enabling: "Enabling",
      active: "Loyalty notifications are active in this browser.",
      blocked: "Notifications are blocked in this browser.",
      notConfigured: "Web Push keys are not configured in Medusa yet.",
      notGranted: "Notification permission was not granted.",
      unsupported: "This browser cannot receive Web Push notifications here.",
      failed: "Could not enable loyalty notifications.",
      noPaidChannels: "No email, SMS, WhatsApp, or paid messaging service.",
    },
    categories: {
      eyebrow: "Shop by category",
      title: "Explore Mouher",
      all: "All",
      shop: "Shop",
    },
    collections: {
      eyebrow: "Collections",
      title: "Shop the edit",
      all: "All edits",
    },
    cart: {
      quickAdd: "Quick add",
      viewDetails: "View details",
      adding: "Adding",
      previewAdded: "Added to preview bag.",
      medusaAdded: "Added to bag.",
      unavailable: "Cart is not available. Check Medusa cart settings.",
      noVariant: "Variant needed",
      bag: "Shopping bag",
      checkout: "Checkout",
      subtotal: "Subtotal",
      empty: "Your bag is empty.",
      quantity: "Quantity",
      increase: "Increase quantity",
      decrease: "Decrease quantity",
      remove: "Remove",
      close: "Close cart",
      account: "Account",
      wishlist: "Add to wishlist",
      stockLow: "Last pieces",
      inStock: "In stock",
      snapPay: "SnapPay installment option prepared for checkout.",
    },
    checkout: {
      title: "Ready for checkout",
      description:
        "Medusa will own cart, inventory, shipping, tax and checkout. SnapPay activation needs merchant credentials and production keys.",
      customer: "Customer",
      delivery: "Delivery",
      payment: "Payment",
      snapPay: "SnapPay installments",
      card: "Card / local payment provider",
      continue: "Continue checkout",
    },
    trust: {
      shipping: "Free shipping above the live €50 equivalent",
      returns: "Easy returns and exchanges",
      support: "Direct Mouher support",
    },
    search: {
      open: "Search",
      title: "Search Mouher",
      placeholder: "Search products, categories...",
      submit: "Search",
      close: "Close search",
    },
    philosophy: {
      eyebrow: "Mouher",
      title: "Made for daily rhythm.",
      description:
        "The storefront keeps the visual language minimal and lets Medusa own the catalog, inventory, cart and pricing logic.",
      button: "About Mouher",
    },
    newsletter: {
      eyebrow: "Mouher updates",
      title: "Latest from Mouher.",
      description: "Collection notes, studio news and private launch updates.",
      placeholder: "Email address",
      button: "Join",
      thanks: "Mamnoon ke be Mouher peyvasti.",
    },
    footer: {
      shop: "Shop",
      information: "Information",
      follow: "Follow",
      newIn: "New edit",
      collections: "Collections",
      allClothing: "All clothing",
      shipping: "Shipping",
      returns: "Returns",
      sizeGuide: "Size guide",
      contact: "Contact",
      instagram: "Instagram",
      pinterest: "Pinterest",
      tiktok: "TikTok",
      copyright: "© 2026 Mouher",
      privacy: "Privacy",
      terms: "Terms",
    },
  },
  farsi: {
    announcement: "ارسال رایگان برای سفارش‌های بالاتر از معادل روز ۵۰ یورو",
    nav: {
      newIn: "کالکشن جدید",
      collections: "کالکشن‌ها",
      shop: "فروشگاه",
      owner: "مالک",
      developer: "توسعه",
      assist: "دستیار",
    },
    hero: {
      eyebrow: "استودیو موهر",
      title: "موهر\nآنچه می‌پوشی",
      description:
        "فروشگاه پوشاک مدرن با پایه مدوسا برای کاتالوگ، سبد خرید و مسیر پرداخت واقعی.",
      button: "دیدن کالکشن",
    },
    products: {
      eyebrow: "کاتالوگ زنده",
      title: "تازه‌ها",
      shopAll: "همه محصولات",
      empty: "محصولی برای این جستجو پیدا نشد.",
      sourceDemo: "کاتالوگ آزمایشی",
      sourceLive: "محصولات mouher.com",
      sourceMedusa: "کاتالوگ مدوسا",
      loading: "در حال بارگذاری",
      viewLive: "دیدن محصول در سایت",
    },
    productPage: {
      back: "بازگشت به فروشگاه",
      details: "جزئیات محصول",
      category: "دسته‌بندی",
      collection: "ادیت",
      sizes: "سایزها",
      colors: "رنگ‌ها",
      stock: "موجودی",
      related: "محصولات مرتبط",
      openLive: "باز کردن در mouher.com",
      loading: "در حال بارگذاری محصول",
      notFoundTitle: "محصول پیدا نشد",
      notFoundDescription: "این محصول در اسنپ‌شات فعلی کاتالوگ موجود نیست.",
    },
    dashboard: {
      ownerEyebrow: "داشبورد مالک",
      ownerTitle: "نمای کلی کسب‌وکار",
      ownerDescription:
        "سیگنال‌های کاتالوگ، موجودی، دسته‌بندی و مرچندایزینگ از اسنپ‌شات محصولات موهر.",
      assistEyebrow: "دستیار سایت",
      assistTitle: "میز پاسخ به مشتری",
      assistDescription:
        "پاسخ سریع محصول، بررسی ویترین و کارهای محتوایی برای دستیار وب‌سایت.",
      viewStore: "دیدن فروشگاه",
      websiteAssist: "دستیار سایت",
      owner: "داشبورد مالک",
      products: "محصولات",
      inventory: "موجودی",
      inStock: "موجود",
      lowStock: "موجودی کم",
      sale: "تخفیف‌دار",
      inventoryValue: "ارزش موجودی",
      categoryMix: "ترکیب دسته‌ها",
      priorityProducts: "محصولات اولویت‌دار",
      operations: "عملیات",
      name: "محصول",
      price: "قیمت",
      status: "وضعیت",
      badge: "برچسب",
      action: "عملیات",
      open: "باز کردن",
      live: "سایت اصلی",
      ready: "آماده",
      needsApi: "نیازمند API",
      developerEyebrow: "فضای توسعه",
      developerTitle: "پیاده‌سازی کامرس",
      developerDescription:
        "وضعیت پروکسی محافظت‌شده ادمین مدوسا، چک‌اوت Store API و ارسال پوش مرورگر.",
      accountEyebrow: "فضای مشتری",
      accountTitle: "آتلیه پروفایل",
      accountDescription:
        "صفحه پروفایل خصوصی برای اطلاعات شخصی، یادداشت استایل، عکس‌ها و دسترسی وفاداری.",
      apiSurface: "سطح API",
      implementationQueue: "صف اجرای کار",
      medusaDomains: "دامنه‌های مدوسا",
      storefront: "فروشگاه",
      backend: "بک‌اند",
      protected: "محافظت‌شده",
      public: "عمومی",
      browserPush: "پوش مرورگر",
      chromeSafari: "کروم / سافاری",
      search: "جستجوی محصول یا سوال مشتری",
      suggestedReply: "پاسخ پیشنهادی",
      productMatches: "محصولات مرتبط",
      contentQueue: "صف محتوا",
      missingPhoto: "عکس محصول ناقص",
      missingColor: "اطلاعات رنگ ناقص",
      missingSize: "اطلاعات سایز ناقص",
      saleBadge: "برچسب تخفیف",
      noTasks: "کار فوری برای سایت وجود ندارد.",
      outOfStock: "ناموجود",
    },
    account: {
      account: "حساب کاربری",
      greeting: "سلام، پرهام",
      orders: "سفارش‌های من",
      myInfo: "اطلاعات من",
      notifications: "اعلان‌ها",
      notifyMeList: "لیست خبرم کن",
      giftCards: "کارت هدیه",
      helpCenter: "مرکز راهنما",
      signOut: "خروج",
      wishlist: "علاقه‌مندی‌ها",
      viewed: "دیده‌شده‌ها",
      recommended: "پیشنهاد برای شما",
      viewAll: "مشاهده همه",
      shopFaster: "با اپ سریع‌تر خرید کن",
      help: "راهنما",
      trackOrder: "پیگیری سفارش",
      shippingInfo: "اطلاعات ارسال",
      returns: "مرجوعی",
      contactUs: "تماس با ما",
      company: "شرکت",
      careers: "فرصت‌های همکاری",
      about: "درباره ما",
      stores: "فروشگاه‌ها",
      ambassadorProgram: "برنامه سفیران",
      quickLinks: "لینک‌های سریع",
      blog: "بلاگ",
      sizeGuide: "راهنمای سایز",
      sitemap: "نقشه سایت",
      checkGiftCardBalance: "بررسی موجودی کارت هدیه",
      loginTitle: "ورود به حساب کاربری",
      createTitle: "ساخت حساب کاربری",
      loginDescription:
        "با یک نشست خصوصی پروفایل، سفارش‌ها، علاقه‌مندی‌ها و اعلان‌ها را مدیریت کن.",
      createDescription:
        "قبل از ذخیره اطلاعات شخصی، حساب موهر را با رمز قوی بساز.",
      login: "ورود",
      createAccount: "ساخت حساب",
      switchToCreate: "ساخت حساب",
      switchToLogin: "حساب دارم",
      password: "رمز عبور",
      passwordPlaceholder: "رمز عبور را وارد کن",
      confirmPassword: "تکرار رمز عبور",
      confirmPasswordPlaceholder: "رمز عبور را تکرار کن",
      showPassword: "نمایش",
      hidePassword: "مخفی",
      authSecurityNote:
        "رمز عبور در مرورگر بررسی می‌شود و اینجا ذخیره نمی‌شود. قبل از پروداکشن این فرم باید به نشست امن HTTPS وصل شود.",
      authRequired: "برای باز کردن داشبورد وارد شو یا حساب بساز.",
      authErrorRequired: "ایمیل و رمز عبور لازم است.",
      authErrorPasswordLength: "حداقل ۸ کاراکتر وارد کن.",
      authErrorPasswordMismatch: "رمزها یکسان نیستند.",
      profileEyebrow: "پروفایل شخصی",
      heroTitle: "پروفایل موهر خودت را بساز",
      heroDescription:
        "اطلاعاتی را اضافه کن که به موهر کمک می‌کند فیت، استایل و روش تماس دلخواهت را به خاطر بسپارد.",
      profilePhoto: "عکس پروفایل",
      coverPhoto: "عکس کاور",
      addPhoto: "افزودن عکس",
      changePhoto: "تغییر عکس",
      gallery: "گالری عکس",
      addGalleryPhoto: "افزودن تصویر",
      profileDetails: "جزئیات پروفایل",
      fullName: "نام کامل",
      fullNamePlaceholder: "نام شما",
      email: "ایمیل",
      emailPlaceholder: "you@example.com",
      phone: "تلفن",
      phonePlaceholder: "+39 ...",
      city: "شهر",
      cityPlaceholder: "میلان",
      styleNotes: "یادداشت استایل",
      styleNotesPlaceholder: "فیت، رنگ، سایز و مناسبت‌های دلخواه",
      saveProfile: "ذخیره پروفایل",
      savedProfile: "پروفایل در همین مرورگر ذخیره شد.",
      previewLabel: "پیش‌نمایش پروفایل",
      emptyName: "نام شما",
      emptyLocation: "شهر و اطلاعات تماس",
      emptyBio: "یادداشت فیت، رنگ‌های محبوب و آیتم‌های دلخواه اینجا نمایش داده می‌شود.",
      browserPush: "پوش مرورگر",
      browserSupported: "در این مرورگر پشتیبانی می‌شود",
      browserUnsupported: "در این مرورگر در دسترس نیست",
      customerId: "شناسه مشتری",
      customerPlaceholder: "cus_...",
      enable: "فعال‌سازی اعلان وفاداری",
      enabling: "در حال فعال‌سازی",
      active: "اعلان‌های وفاداری در این مرورگر فعال است.",
      blocked: "اعلان‌ها در این مرورگر مسدود شده‌اند.",
      notConfigured: "کلیدهای Web Push هنوز در جنگو تنظیم نشده‌اند.",
      notGranted: "اجازه اعلان داده نشد.",
      unsupported: "این مرورگر اینجا نمی‌تواند Web Push دریافت کند.",
      failed: "فعال‌سازی اعلان وفاداری ممکن نشد.",
      noPaidChannels: "بدون ایمیل، پیامک، واتساپ یا سرویس پیام‌رسان پولی.",
    },
    categories: {
      eyebrow: "دسته‌بندی",
      title: "موهر را کشف کن",
      all: "همه",
      shop: "مشاهده",
    },
    collections: {
      eyebrow: "کالکشن‌ها",
      title: "انتخاب کالکشن",
      all: "همه کالکشن‌ها",
    },
    cart: {
      quickAdd: "افزودن سریع",
      viewDetails: "جزئیات",
      adding: "در حال افزودن",
      previewAdded: "به سبد آزمایشی اضافه شد.",
      medusaAdded: "به سبد خرید اضافه شد.",
      unavailable: "سبد خرید در دسترس نیست. تنظیمات مدوسا را بررسی کن.",
      noVariant: "نیاز به وریانت",
      bag: "سبد خرید",
      checkout: "پرداخت",
      subtotal: "جمع سبد",
      empty: "سبد خرید خالی است.",
      quantity: "تعداد",
      increase: "افزایش تعداد",
      decrease: "کاهش تعداد",
      remove: "حذف",
      close: "بستن سبد خرید",
      account: "حساب کاربری",
      wishlist: "افزودن به علاقه‌مندی‌ها",
      stockLow: "آخرین موجودی",
      inStock: "موجود",
      snapPay: "گزینه پرداخت اقساطی SnapPay برای چک‌اوت آماده شده است.",
    },
    checkout: {
      title: "آماده مسیر پرداخت",
      description:
        "مدوسا مسئول سبد، موجودی، ارسال، مالیات و پرداخت است. فعال‌سازی SnapPay به اطلاعات پذیرنده و کلیدهای پروداکشن نیاز دارد.",
      customer: "مشتری",
      delivery: "ارسال",
      payment: "پرداخت",
      snapPay: "اقساط SnapPay",
      card: "کارت / درگاه محلی",
      continue: "ادامه پرداخت",
    },
    trust: {
      shipping: "ارسال رایگان بالای معادل روز ۵۰ یورو",
      returns: "تعویض و مرجوعی آسان",
      support: "پشتیبانی مستقیم موهر",
    },
    search: {
      open: "جستجو",
      title: "جستجو در موهر",
      placeholder: "جستجوی محصول یا دسته‌بندی...",
      submit: "جستجو",
      close: "بستن جستجو",
    },
    philosophy: {
      eyebrow: "موهر",
      title: "برای ریتم روزمره.",
      description:
        "ظاهر سایت ساده می‌ماند و مدوسا مسئول کاتالوگ، موجودی، قیمت‌گذاری و سبد خرید است.",
      button: "درباره موهر",
    },
    newsletter: {
      eyebrow: "خبرهای موهر",
      title: "تازه‌های موهر.",
      description: "یادداشت‌های کالکشن، خبرهای استودیو و لانچ‌های خصوصی.",
      placeholder: "ایمیل شما",
      button: "عضویت",
      thanks: "ممنون که به موهر پیوستی.",
    },
    footer: {
      shop: "فروشگاه",
      information: "اطلاعات",
      follow: "دنبال کردن",
      newIn: "کالکشن جدید",
      collections: "کالکشن‌ها",
      allClothing: "همه محصولات",
      shipping: "ارسال",
      returns: "مرجوعی",
      sizeGuide: "راهنمای اندازه",
      contact: "تماس",
      instagram: "اینستاگرام",
      pinterest: "پینترست",
      tiktok: "تیک‌تاک",
      copyright: "© ۱۴۰۵ موهر",
      privacy: "حریم خصوصی",
      terms: "قوانین",
    },
  },
};