package system

func openAPIV1AccountSchemas() map[string]any {
	return map[string]any{
		"SiteMember": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"id":       map[string]any{"type": "string", "format": "uuid"},
				"user_id":  map[string]any{"type": "string", "format": "uuid"},
				"email":    map[string]any{"type": "string", "format": "email"},
				"role":     map[string]any{"type": "string"},
				"added_at": map[string]any{"type": "string", "format": "date-time"},
			},
		},
		"Team": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"id":           map[string]any{"type": "string", "format": "uuid"},
				"name":         map[string]any{"type": "string"},
				"logo_url":     map[string]any{"type": "string"},
				"role":         map[string]any{"type": "string"},
				"created_at":   map[string]any{"type": "string", "format": "date-time"},
				"usage":        map[string]any{"$ref": "#/components/schemas/TeamUsageSummary"},
				"entitlements": map[string]any{"$ref": "#/components/schemas/TeamEntitlements"},
				"plan":         map[string]any{"$ref": "#/components/schemas/TeamPlan"},
			},
		},
		"TeamUsageSummary": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"current_sites":           map[string]any{"type": "integer"},
				"current_members":         map[string]any{"type": "integer"},
				"current_pending_invites": map[string]any{"type": "integer"},
			},
		},
		"TeamEntitlements": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"max_sites_per_team":               map[string]any{"type": "integer"},
				"max_team_members":                 map[string]any{"type": "integer"},
				"max_retention_days":               map[string]any{"type": "integer"},
				"allow_sso":                        map[string]any{"type": "boolean"},
				"allow_custom_branding":            map[string]any{"type": "boolean"},
				"allow_external_report_recipients": map[string]any{"type": "boolean", "description": "Whether scheduled reports may be sent to confirmed addresses outside the team."},
			},
		},
		"SSOAvailability": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"enabled": map[string]any{"type": "boolean"},
			},
			"required": []string{"enabled"},
		},
		"SSOStartRequest": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"email":        map[string]any{"type": "string", "format": "email"},
				"invite_token": map[string]any{"type": "string", "description": "Invitation token used instead of email when starting SSO from invitation acceptance."},
				"return_url":   map[string]any{"type": "string", "description": "Optional same-origin application path. Unsafe or authentication paths fall back to /."},
				"remember_me":  map[string]any{"type": "boolean"},
			},
			"oneOf": []any{
				map[string]any{"required": []string{"email"}},
				map[string]any{"required": []string{"invite_token"}},
			},
		},
		"SSOStartResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"auth_url": map[string]any{"type": "string", "format": "uri"},
			},
			"required": []string{"auth_url"},
		},
		"SocialProvider": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"id":           map[string]any{"type": "string", "enum": []string{"google", "github", "microsoft"}},
				"display_name": map[string]any{"type": "string"},
			},
			"required": []string{"id", "display_name"},
		},
		"SocialProvidersResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"providers":      map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/SocialProvider"}},
				"signup_enabled": map[string]any{"type": "boolean"},
			},
			"required": []string{"providers", "signup_enabled"},
		},
		"SocialStartRequest": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"flow":         map[string]any{"type": "string", "enum": []string{"login", "signup", "invite"}},
				"invite_token": map[string]any{"type": "string"},
				"return_url":   map[string]any{"type": "string", "description": "Optional safe local application path."},
				"remember_me":  map[string]any{"type": "boolean"},
			},
			"required": []string{"flow"},
		},
		"SocialCompleteRequest": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"completion_token": map[string]any{"type": "string", "writeOnly": true},
				"email":            map[string]any{"type": "string", "format": "email", "description": "HitKeep target email required for a first unauthenticated Microsoft link."},
			},
			"required": []string{"completion_token"},
		},
		"SocialPreviewResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"provider":                    map[string]any{"type": "string", "enum": []string{"google", "github", "microsoft"}},
				"display_name":                map[string]any{"type": "string"},
				"observed_email":              map[string]any{"type": "string", "format": "email"},
				"email_verified":              map[string]any{"type": "boolean"},
				"email_confirmation_required": map[string]any{"type": "boolean", "description": "Whether this completion requires the user to confirm a HitKeep email before continuing."},
				"flow":                        map[string]any{"type": "string", "enum": []string{"login", "signup", "invite"}},
			},
			"required": []string{"provider", "display_name", "email_verified", "email_confirmation_required", "flow"},
		},
		"SocialCompleteResponse": map[string]any{
			"allOf": []any{
				map[string]any{"$ref": "#/components/schemas/LoginResponse"},
				map[string]any{"type": "object", "properties": map[string]any{
					"status":           map[string]any{"type": "string", "enum": []string{"ok", "mfa_required", "signup_required", "verification_sent"}},
					"redirect_url":     map[string]any{"type": "string"},
					"completion_token": map[string]any{"type": "string", "readOnly": true, "description": "Replacement one-time token returned only when signup details are required."},
				}, "required": []string{"status"}},
			},
		},
		"SocialSignupCompleteRequest": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"completion_token": map[string]any{"type": "string", "writeOnly": true},
				"email":            map[string]any{"type": "string", "format": "email"},
				"team_name":        map[string]any{"type": "string", "maxLength": 120},
				"plan_code":        map[string]any{"type": "string", "enum": []string{"free", "pro", "business"}},
				"billing":          map[string]any{"type": "string", "enum": []string{"monthly", "annual"}},
				"jurisdiction":     map[string]any{"type": "string", "enum": []string{"EU", "US"}},
				"locale":           map[string]any{"type": "string"},
				"accepted_tos":     map[string]any{"type": "boolean"},
			},
			"required": []string{"completion_token", "team_name", "plan_code", "billing", "jurisdiction", "locale", "accepted_tos"},
		},
		"SocialSignupCompleteResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"status":       map[string]any{"type": "string", "enum": []string{"ok", "verification_sent"}},
				"plan_code":    map[string]any{"type": "string"},
				"billing":      map[string]any{"type": "string"},
				"redirect_url": map[string]any{"type": "string"},
			},
			"required": []string{"status", "plan_code", "billing"},
		},
		"TeamSSOInput": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"provider_type":      map[string]any{"type": "string", "enum": []string{"oidc"}},
				"issuer_url":         map[string]any{"type": "string", "format": "uri", "maxLength": 2048},
				"client_id":          map[string]any{"type": "string", "maxLength": 512},
				"client_secret":      map[string]any{"type": "string", "writeOnly": true, "description": "Required on create. Blank preserves the stored secret on update."},
				"allowed_domains":    map[string]any{"type": "array", "minItems": 1, "maxItems": 50, "items": map[string]any{"type": "string"}},
				"email_claim":        map[string]any{"type": "string", "default": "email"},
				"display_name_claim": map[string]any{"type": "string", "default": "name"},
				"auto_provision":     map[string]any{"type": "boolean", "description": "When true, verified users from trusted domains may join this team as Members without an invitation. Managed-cloud seat and team limits still apply."},
				"enabled":            map[string]any{"type": "boolean"},
			},
			"required": []string{"provider_type", "issuer_url", "client_id", "allowed_domains", "email_claim", "display_name_claim", "auto_provision", "enabled"},
		},
		"TeamSSOConfig": map[string]any{
			"type":        "object",
			"description": "Redacted team OIDC configuration. The client secret is never returned.",
			"properties": map[string]any{
				"provider_type":            map[string]any{"type": "string", "enum": []string{"oidc"}},
				"issuer_url":               map[string]any{"type": "string", "format": "uri"},
				"client_id":                map[string]any{"type": "string"},
				"client_secret_configured": map[string]any{"type": "boolean"},
				"allowed_domains":          map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				"email_claim":              map[string]any{"type": "string"},
				"display_name_claim":       map[string]any{"type": "string"},
				"auto_provision":           map[string]any{"type": "boolean"},
				"enabled":                  map[string]any{"type": "boolean"},
				"callback_url":             map[string]any{"type": "string", "format": "uri"},
				"updated_at":               map[string]any{"type": "string", "format": "date-time"},
			},
			"required": []string{"provider_type", "issuer_url", "client_id", "client_secret_configured", "allowed_domains", "email_claim", "display_name_claim", "auto_provision", "enabled", "callback_url"},
		},
		"TeamPlan": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"code":        map[string]any{"type": "string"},
				"name":        map[string]any{"type": "string"},
				"upgrade_url": map[string]any{"type": "string"},
				"support_url": map[string]any{"type": "string"},
			},
		},
		"CloudStatus": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"hosted":         map[string]any{"type": "boolean"},
				"signup_enabled": map[string]any{"type": "boolean"},
				"jurisdiction":   map[string]any{"type": "string"},
				"region":         map[string]any{"type": "string"},
				"upgrade_url":    map[string]any{"type": "string"},
				"support_url":    map[string]any{"type": "string"},
			},
		},
		"AskAIStatus": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"enabled":          map[string]any{"type": "boolean"},
				"available":        map[string]any{"type": "boolean"},
				"status":           map[string]any{"type": "string", "enum": []string{"disabled", "not_configured", "available", "budget_exhausted"}},
				"provider":         map[string]any{"type": "string"},
				"model":            map[string]any{"type": "string"},
				"budget_exhausted": map[string]any{"type": "boolean"},
			},
			"required": []string{"enabled", "available", "status", "budget_exhausted"},
		},
		"TeamMember": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"id":       map[string]any{"type": "string", "format": "uuid"},
				"user_id":  map[string]any{"type": "string", "format": "uuid"},
				"email":    map[string]any{"type": "string", "format": "email"},
				"role":     map[string]any{"type": "string"},
				"added_at": map[string]any{"type": "string", "format": "date-time"},
			},
		},
		"TeamInvite": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"id":              map[string]any{"type": "string", "format": "uuid"},
				"team_id":         map[string]any{"type": "string", "format": "uuid"},
				"email":           map[string]any{"type": "string", "format": "email"},
				"role":            map[string]any{"type": "string"},
				"invited_user_id": map[string]any{"type": "string", "format": "uuid"},
				"status":          map[string]any{"type": "string"},
				"created_by":      map[string]any{"type": "string", "format": "uuid"},
				"created_at":      map[string]any{"type": "string", "format": "date-time"},
				"expires_at":      map[string]any{"type": "string", "format": "date-time"},
				"accepted_at":     map[string]any{"type": "string", "format": "date-time"},
				"revoked_at":      map[string]any{"type": "string", "format": "date-time"},
			},
		},
		"TeamAuditEntry": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"id":                   map[string]any{"type": "string", "format": "uuid"},
				"team_id":              map[string]any{"type": "string", "format": "uuid"},
				"action":               map[string]any{"type": "string"},
				"details":              map[string]any{"type": "string"},
				"actor_user_id":        map[string]any{"type": "string", "format": "uuid"},
				"actor_email":          map[string]any{"type": "string", "format": "email"},
				"actor_email_snapshot": map[string]any{"type": "string"},
				"actor_role_snapshot":  map[string]any{"type": "string"},
				"target_user_id":       map[string]any{"type": "string", "format": "uuid"},
				"target_email":         map[string]any{"type": "string", "format": "email"},
				"target_type":          map[string]any{"type": "string"},
				"target_id":            map[string]any{"type": "string"},
				"target_label":         map[string]any{"type": "string"},
				"outcome":              map[string]any{"type": "string"},
				"ip_address":           map[string]any{"type": "string"},
				"ip_country_code":      map[string]any{"type": "string"},
				"user_agent":           map[string]any{"type": "string"},
				"request_id":           map[string]any{"type": "string"},
				"created_at":           map[string]any{"type": "string", "format": "date-time"},
			},
		},
		"TeamAuditListResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"entries": map[string]any{
					"type":  "array",
					"items": map[string]any{"$ref": "#/components/schemas/TeamAuditEntry"},
				},
				"total":    map[string]any{"type": "integer"},
				"limit":    map[string]any{"type": "integer"},
				"offset":   map[string]any{"type": "integer"},
				"has_more": map[string]any{"type": "boolean"},
				"action":   map[string]any{"type": "string"},
			},
		},
		"TeamListResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"active_team_id": map[string]any{"type": "string", "format": "uuid"},
				"recent_team_ids": map[string]any{
					"type":  "array",
					"items": map[string]any{"type": "string", "format": "uuid"},
				},
				"teams": map[string]any{
					"type":  "array",
					"items": map[string]any{"$ref": "#/components/schemas/Team"},
				},
			},
		},
		"TeamActiveResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"status":         map[string]any{"type": "string"},
				"active_team_id": map[string]any{"type": "string", "format": "uuid"},
				"recent_team_ids": map[string]any{
					"type":  "array",
					"items": map[string]any{"type": "string", "format": "uuid"},
				},
			},
		},
		"TeamCreateResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"team": map[string]any{"$ref": "#/components/schemas/Team"},
			},
		},
		"TeamLeaveResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"status":         map[string]any{"type": "string"},
				"active_team_id": map[string]any{"type": "string", "format": "uuid"},
				"recent_team_ids": map[string]any{
					"type":  "array",
					"items": map[string]any{"type": "string", "format": "uuid"},
				},
			},
		},
		"TeamArchiveResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"status":         map[string]any{"type": "string"},
				"active_team_id": map[string]any{"type": "string", "format": "uuid"},
				"recent_team_ids": map[string]any{
					"type":  "array",
					"items": map[string]any{"type": "string", "format": "uuid"},
				},
			},
		},
		"AdminTeam": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"id":           map[string]any{"type": "string", "format": "uuid"},
				"name":         map[string]any{"type": "string"},
				"is_default":   map[string]any{"type": "boolean"},
				"is_archived":  map[string]any{"type": "boolean"},
				"member_count": map[string]any{"type": "integer"},
				"site_count":   map[string]any{"type": "integer"},
				"created_at":   map[string]any{"type": "string", "format": "date-time"},
			},
		},
		"AdminDeleteTeamResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"status":  map[string]any{"type": "string"},
				"team_id": map[string]any{"type": "string", "format": "uuid"},
				"name":    map[string]any{"type": "string"},
			},
		},
		"AdminDisableUserMFAResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"status":               map[string]any{"type": "string"},
				"totp_disabled":        map[string]any{"type": "boolean"},
				"passkeys_deleted":     map[string]any{"type": "integer"},
				"sessions_invalidated": map[string]any{"type": "integer"},
			},
			"required": []string{"status", "totp_disabled", "passkeys_deleted", "sessions_invalidated"},
		},
		"SystemFeatureStatus": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"key":     map[string]any{"type": "string", "description": "Stable feature key."},
				"enabled": map[string]any{"type": "boolean"},
				"detail":  map[string]any{"type": "string", "description": "Optional non-sensitive runtime detail, such as target type or path."},
			},
			"required": []string{"key", "enabled"},
		},
		"SystemInfo": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"version":          map[string]any{"type": "string"},
				"runtime_mode":     map[string]any{"type": "string"},
				"uptime":           map[string]any{"type": "string"},
				"public_url":       map[string]any{"type": "string"},
				"enabled_features": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/SystemFeatureStatus"}},
				"config_flags":     map[string]any{"type": "object", "additionalProperties": true},
			},
		},
		"SystemAIStatus": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"status":                map[string]any{"type": "string", "enum": []string{"disabled", "not_configured", "configured", "budget_exhausted", "needs_attention"}},
				"enabled":               map[string]any{"type": "boolean"},
				"configured":            map[string]any{"type": "boolean"},
				"ask_ai_enabled":        map[string]any{"type": "boolean"},
				"ask_ai_available":      map[string]any{"type": "boolean"},
				"config_mode":           map[string]any{"type": "string", "enum": []string{"cloud_managed", "self_hosted"}},
				"provider":              map[string]any{"type": "string"},
				"model":                 map[string]any{"type": "string"},
				"base_url_configured":   map[string]any{"type": "boolean"},
				"region":                map[string]any{"type": "string"},
				"last_success_at":       map[string]any{"type": "string", "format": "date-time"},
				"last_attempt_at":       map[string]any{"type": "string", "format": "date-time"},
				"last_error_category":   map[string]any{"type": "string"},
				"requests_used":         map[string]any{"type": "integer"},
				"request_limit":         map[string]any{"type": "integer"},
				"tokens_used":           map[string]any{"type": "integer"},
				"token_limit":           map[string]any{"type": "integer"},
				"budget_window_minutes": map[string]any{"type": "integer"},
				"budget_exhausted":      map[string]any{"type": "boolean"},
			},
			"required": []string{"status", "enabled", "configured", "ask_ai_enabled", "ask_ai_available", "config_mode", "base_url_configured", "requests_used", "request_limit", "tokens_used", "token_limit", "budget_window_minutes", "budget_exhausted"},
		},
		"SystemHealth": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"status":    map[string]any{"type": "string"},
				"database":  map[string]any{"type": "string"},
				"workers":   map[string]any{"type": "string"},
				"is_leader": map[string]any{"type": "boolean"},
			},
		},
		"SystemSearchConsoleStatus": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"status":                map[string]any{"type": "string", "enum": []string{"healthy", "idle", "syncing", "degraded", "needs_attention", "not_configured"}},
				"credentials_status":    map[string]any{"type": "string", "enum": []string{"configured", "missing"}},
				"worker_status":         map[string]any{"type": "string", "enum": []string{"enabled", "disabled"}},
				"sync_status":           map[string]any{"type": "string", "enum": []string{"healthy", "idle", "pending", "running", "failed", "needs_attention"}},
				"connected_teams":       map[string]any{"type": "integer"},
				"mapped_sites":          map[string]any{"type": "integer"},
				"pending_syncs":         map[string]any{"type": "integer"},
				"running_syncs":         map[string]any{"type": "integer"},
				"failed_syncs":          map[string]any{"type": "integer"},
				"needs_attention_syncs": map[string]any{"type": "integer"},
				"last_success_at":       map[string]any{"type": "string", "format": "date-time"},
				"last_attempt_at":       map[string]any{"type": "string", "format": "date-time"},
				"next_retry_at":         map[string]any{"type": "string", "format": "date-time"},
			},
			"required": []string{"status", "credentials_status", "worker_status", "sync_status", "connected_teams", "mapped_sites", "pending_syncs", "running_syncs", "failed_syncs", "needs_attention_syncs"},
		},
		"TenantDBInfo": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"tenant_id":  map[string]any{"type": "string", "format": "uuid"},
				"name":       map[string]any{"type": "string"},
				"is_default": map[string]any{"type": "boolean"},
				"bytes":      map[string]any{"type": "integer", "format": "int64"},
				"path":       map[string]any{"type": "string"},
			},
		},
		"SystemStorage": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"shared_db_path":       map[string]any{"type": "string"},
				"shared_db_bytes":      map[string]any{"type": "integer", "format": "int64"},
				"data_path":            map[string]any{"type": "string"},
				"tenant_db_count":      map[string]any{"type": "integer"},
				"tenant_dbs":           map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/TenantDBInfo"}},
				"spam_cache_path":      map[string]any{"type": "string"},
				"backup_path":          map[string]any{"type": "string"},
				"disk_available_bytes": map[string]any{"type": "integer", "format": "int64"},
				"disk_total_bytes":     map[string]any{"type": "integer", "format": "int64"},
				"duckdb_memory":        map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/DuckDBMemoryStat"}},
			},
		},
		"DuckDBMemoryStat": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"tag":                     map[string]any{"type": "string"},
				"memory_bytes":            map[string]any{"type": "integer", "format": "int64"},
				"temporary_storage_bytes": map[string]any{"type": "integer", "format": "int64"},
			},
		},
		"SystemIngestStats": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"recent_hits":       map[string]any{"type": "integer"},
				"recent_events":     map[string]any{"type": "integer"},
				"recent_rejections": map[string]any{"type": "integer"},
				"recent_spam":       map[string]any{"type": "integer"},
				"hits_per_second":   map[string]any{"type": "number", "format": "double"},
			},
		},
		"SystemBackupStatus": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"enabled":         map[string]any{"type": "boolean"},
				"config_path":     map[string]any{"type": "string"},
				"interval_min":    map[string]any{"type": "integer"},
				"retention":       map[string]any{"type": "integer"},
				"last_backup":     map[string]any{"type": "string", "format": "date-time"},
				"next_backup":     map[string]any{"type": "string", "format": "date-time"},
				"last_failed_at":  map[string]any{"type": "string", "format": "date-time"},
				"last_error":      map[string]any{"type": "string"},
				"recent_failures": map[string]any{"type": "integer"},
			},
		},
		"SystemDatabaseStatus": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"recovery_enabled":               map[string]any{"type": "boolean"},
				"automatic_wal_recovery_enabled": map[string]any{"type": "boolean"},
				"recovery_bundle_available":      map[string]any{"type": "boolean"},
				"removed_unsafe_indexes":         map[string]any{"type": "integer"},
				"checkpoint_interval_min":        map[string]any{"type": "integer"},
				"last_checkpoint_at":             map[string]any{"type": "string", "format": "date-time"},
				"last_checkpoint_error":          map[string]any{"type": "string"},
				"last_recovery_at":               map[string]any{"type": "string", "format": "date-time"},
			},
		},
		"SystemSpamStatus": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"db_path":      map[string]any{"type": "string"},
				"last_refresh": map[string]any{"type": "string", "format": "date-time"},
				"rule_count":   map[string]any{"type": "integer"},
				"auto_update":  map[string]any{"type": "boolean"},
				"last_error":   map[string]any{"type": "string"},
			},
		},
		"ImportStageCleanupRunResult": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"imports_cleaned":       map[string]any{"type": "integer"},
				"files_cleaned":         map[string]any{"type": "integer"},
				"bytes_cleaned":         map[string]any{"type": "integer", "format": "int64"},
				"imports_marked_failed": map[string]any{"type": "integer"},
				"errors":                map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
			},
		},
		"SystemImportStageCleanupStatus": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"enabled":              map[string]any{"type": "boolean"},
				"retention_days":       map[string]any{"type": "integer"},
				"stale_imports":        map[string]any{"type": "integer"},
				"stale_files":          map[string]any{"type": "integer"},
				"stale_bytes":          map[string]any{"type": "integer", "format": "int64"},
				"last_run":             map[string]any{"type": "string", "format": "date-time"},
				"last_failed_at":       map[string]any{"type": "string", "format": "date-time"},
				"last_error":           map[string]any{"type": "string"},
				"recent_failures":      map[string]any{"type": "integer"},
				"last_cleaned_imports": map[string]any{"type": "integer"},
				"last_cleaned_files":   map[string]any{"type": "integer"},
				"last_cleaned_bytes":   map[string]any{"type": "integer", "format": "int64"},
				"last_marked_failed":   map[string]any{"type": "integer"},
			},
		},
		"SystemCacheEntry": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"size":     map[string]any{"type": "integer"},
				"max_size": map[string]any{"type": "integer"},
				"ttl":      map[string]any{"type": "string"},
			},
		},
		"SystemCacheStatus": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"permissions_cache":  map[string]any{"$ref": "#/components/schemas/SystemCacheEntry"},
				"api_client_cache":   map[string]any{"$ref": "#/components/schemas/SystemCacheEntry"},
				"rate_limiter_cache": map[string]any{"$ref": "#/components/schemas/SystemCacheEntry"},
				"status":             map[string]any{"type": "string"},
			},
		},
		"SystemMailStatus": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"configured":   map[string]any{"type": "boolean"},
				"driver":       map[string]any{"type": "string"},
				"host":         map[string]any{"type": "string"},
				"port":         map[string]any{"type": "integer"},
				"encryption":   map[string]any{"type": "string"},
				"from_address": map[string]any{"type": "string"},
				"from_name":    map[string]any{"type": "string"},
				"username":     map[string]any{"type": "string"},
				"password_set": map[string]any{"type": "boolean"},
				"last_test_at": map[string]any{"type": "string", "format": "date-time"},
				"last_test_ok": map[string]any{"type": "boolean"},
			},
		},
		"SystemActionResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"status":  map[string]any{"type": "string"},
				"message": map[string]any{"type": "string"},
			},
		},
		"SystemImportStageCleanupRunResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"status":  map[string]any{"type": "string"},
				"message": map[string]any{"type": "string"},
				"result":  map[string]any{"$ref": "#/components/schemas/ImportStageCleanupRunResult"},
			},
		},
		"InstanceAuditEntry": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"id":                   map[string]any{"type": "string", "format": "uuid"},
				"created_at":           map[string]any{"type": "string", "format": "date-time"},
				"actor_id":             map[string]any{"type": "string", "format": "uuid"},
				"team_id":              map[string]any{"type": "string", "format": "uuid"},
				"target_user_id":       map[string]any{"type": "string", "format": "uuid"},
				"actor_email_snapshot": map[string]any{"type": "string"},
				"actor_role_snapshot":  map[string]any{"type": "string"},
				"action":               map[string]any{"type": "string"},
				"target_type":          map[string]any{"type": "string"},
				"target_id":            map[string]any{"type": "string"},
				"target_label":         map[string]any{"type": "string"},
				"outcome":              map[string]any{"type": "string"},
				"ip_address":           map[string]any{"type": "string"},
				"ip_country_code":      map[string]any{"type": "string"},
				"user_agent":           map[string]any{"type": "string"},
				"request_id":           map[string]any{"type": "string"},
				"details":              map[string]any{"type": "string"},
			},
		},
		"InstanceAuditListResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"entries":  map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/InstanceAuditEntry"}},
				"total":    map[string]any{"type": "integer"},
				"limit":    map[string]any{"type": "integer"},
				"offset":   map[string]any{"type": "integer"},
				"has_more": map[string]any{"type": "boolean"},
			},
		},
		"SystemActivationRow": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"team_id":         map[string]any{"type": "string", "format": "uuid"},
				"team_name":       map[string]any{"type": "string"},
				"owner_email":     map[string]any{"type": "string", "format": "email"},
				"plan_code":       map[string]any{"type": "string"},
				"plan_name":       map[string]any{"type": "string"},
				"cloud_region":    map[string]any{"type": "string"},
				"site_id":         map[string]any{"type": "string", "format": "uuid"},
				"site_domain":     map[string]any{"type": "string"},
				"sites_count":     map[string]any{"type": "integer"},
				"active_sites":    map[string]any{"type": "integer"},
				"status":          map[string]any{"type": "string", "enum": []string{"waiting", "live", "dormant", "domain_mismatch"}},
				"first_hit_at":    map[string]any{"type": "string", "format": "date-time"},
				"last_hit_at":     map[string]any{"type": "string", "format": "date-time"},
				"last_event_at":   map[string]any{"type": "string", "format": "date-time"},
				"last_event_name": map[string]any{"type": "string"},
				"hits_last_24h":   map[string]any{"type": "integer"},
				"hits_last_7d":    map[string]any{"type": "integer"},
				"events_last_7d":  map[string]any{"type": "integer"},
				"tracker_source":  map[string]any{"type": "string"},
				"tracker_version": map[string]any{"type": "string"},
			},
		},
		"SystemActivationResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"rows":     map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/SystemActivationRow"}},
				"total":    map[string]any{"type": "integer"},
				"limit":    map[string]any{"type": "integer"},
				"offset":   map[string]any{"type": "integer"},
				"has_more": map[string]any{"type": "boolean"},
			},
		},
		"IPExclusion": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"id":      map[string]any{"type": "string", "format": "uuid"},
				"scope":   map[string]any{"type": "string", "enum": []string{"instance", "team", "site"}, "description": "Scope that owns this rule."},
				"team_id": map[string]any{"type": "string", "format": "uuid", "description": "Owning team for team rules."},
				"site_id": map[string]any{"type": "string", "format": "uuid", "description": "Owning site for site rules."},
				"type":    map[string]any{"type": "string", "enum": []string{"cidr", "country", "user_agent", "path"}},
				"cidr":    map[string]any{"type": "string", "description": "Normalized IP or CIDR value for cidr rules."},
				"country_code": map[string]any{
					"type":        "string",
					"description": "Uppercase ISO 3166-1 alpha-2 country code for country rules.",
				},
				"user_agent":  map[string]any{"type": "string", "description": "Case-insensitive user-agent substring for user_agent rules."},
				"path":        map[string]any{"type": "string", "description": "Normalized, query-free, case-sensitive path matched on segment boundaries."},
				"description": map[string]any{"type": "string"},
				"created_at":  map[string]any{"type": "string", "format": "date-time"},
				"created_by":  map[string]any{"type": "string", "format": "uuid", "description": "Creator ID. Omitted from inherited rows returned across scopes."},
				"inherited":   map[string]any{"type": "boolean", "description": "True when returned through a child scope's effective read."},
			},
			"required": []string{"id", "type", "created_at", "inherited"},
		},
		"IPExclusionCreateRequest": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"type": map[string]any{"type": "string", "enum": []string{"cidr", "country", "user_agent", "path"}, "description": "Rule type. Omitted cidr requests remain accepted for backward compatibility."},
				"cidr": map[string]any{"type": "string", "description": "IP or CIDR value for cidr rules. Plain IP values are normalized to /32 (IPv4) or /128 (IPv6)."},
				"country_code": map[string]any{
					"type":        "string",
					"description": "ISO 3166-1 alpha-2 country code for country rules. Values are normalized to uppercase.",
				},
				"user_agent":  map[string]any{"type": "string", "minLength": 1, "description": "Case-insensitive substring for user_agent rules. Leading and trailing whitespace is removed."},
				"path":        map[string]any{"type": "string", "minLength": 1, "description": "Path rule. Query and fragment are removed; duplicate or trailing slashes and dot segments are normalized before case-sensitive segment-boundary matching."},
				"description": map[string]any{"type": "string", "maxLength": 255},
			},
		},
		"UserProfile": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"id":           map[string]any{"type": "string", "format": "uuid"},
				"email":        map[string]any{"type": "string", "format": "email"},
				"given_name":   map[string]any{"type": "string"},
				"last_name":    map[string]any{"type": "string"},
				"display_name": map[string]any{"type": "string"},
				"avatar_url":   map[string]any{"type": "string"},
			},
		},
		"UserPreferences": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"default_locale":          map[string]any{"type": "string"},
				"dismissed_onboarding_at": map[string]any{"type": "string", "format": "date-time"},
			},
		},
		"SystemStatus": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"needs_setup":   map[string]any{"type": "boolean"},
				"version":       map[string]any{"type": "string"},
				"cloud":         map[string]any{"$ref": "#/components/schemas/CloudStatus"},
				"ask_ai":        map[string]any{"$ref": "#/components/schemas/AskAIStatus"},
				"mail_delivery": map[string]any{"$ref": "#/components/schemas/MailDeliveryStatus"},
			},
		},
		"MailDeliveryStatus": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"available": map[string]any{"type": "boolean"},
				"status":    map[string]any{"type": "string", "enum": []string{"available", "unavailable"}},
			},
			"required": []string{"available", "status"},
		},
		"AskAIFilter": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"type":  map[string]any{"type": "string"},
				"value": map[string]any{"type": "string"},
			},
			"required": []string{"type", "value"},
		},
		"AskAIMessage": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"role":    map[string]any{"type": "string", "enum": []string{"user", "assistant"}},
				"content": map[string]any{"type": "string"},
			},
			"required": []string{"role", "content"},
		},
		"AskAIRequest": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"query":   map[string]any{"type": "string"},
				"from":    map[string]any{"type": "string", "format": "date"},
				"to":      map[string]any{"type": "string", "format": "date"},
				"route":   map[string]any{"type": "string"},
				"filters": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/AskAIFilter"}},
				"history": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/AskAIMessage"}},
			},
			"required": []string{"query"},
		},
		"AskAICitation": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"label":        map[string]any{"type": "string"},
				"tool_call_id": map[string]any{"type": "string"},
			},
			"required": []string{"label", "tool_call_id"},
		},
		"AskAIChartSeries": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"key":   map[string]any{"type": "string"},
				"label": map[string]any{"type": "string"},
			},
			"required": []string{"key", "label"},
		},
		"AskAIChart": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"type":   map[string]any{"type": "string", "enum": []string{"line", "bar", "table"}},
				"title":  map[string]any{"type": "string"},
				"x_key":  map[string]any{"type": "string"},
				"series": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/AskAIChartSeries"}},
				"rows": map[string]any{
					"type": "array",
					"items": map[string]any{
						"type":                 "object",
						"additionalProperties": map[string]any{"type": []string{"string", "number", "boolean", "null"}},
					},
				},
			},
			"required": []string{"type", "title", "rows"},
		},
		"AskAIAction": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"type":   map[string]any{"type": "string", "enum": []string{"navigate", "download_export"}},
				"label":  map[string]any{"type": "string"},
				"target": map[string]any{"type": "string"},
				"format": map[string]any{"type": "string", "enum": []string{"xlsx", "json", "csv", "ndjson"}},
			},
			"required": []string{"type", "label", "target"},
		},
		"AskAIResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"run_id":          map[string]any{"type": "string", "format": "uuid"},
				"answer_markdown": map[string]any{"type": "string"},
				"citations":       map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/AskAICitation"}},
				"charts":          map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/AskAIChart"}},
				"actions":         map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/AskAIAction"}},
			},
			"required": []string{"run_id", "answer_markdown", "citations", "charts", "actions"},
		},
		"AskAIStreamEvent": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"type":           map[string]any{"type": "string", "enum": []string{"progress", "delta", "final", "error"}},
				"status":         map[string]any{"type": "string"},
				"message_key":    map[string]any{"type": "string", "description": "Dashboard i18n key for safe progress or error copy."},
				"tool_call_id":   map[string]any{"type": "string", "description": "Provider-assigned tool call identifier for progress events."},
				"tool_name":      map[string]any{"type": "string", "description": "Safe HitKeep analytics tool identifier for progress events."},
				"delta_markdown": map[string]any{"type": "string", "description": "Session-only markdown answer delta. Final charts, actions, and citations are returned only on final events."},
				"response":       map[string]any{"$ref": "#/components/schemas/AskAIResponse"},
				"error":          map[string]any{"type": "string", "description": "Stable non-secret error label when an in-stream failure occurs."},
			},
			"required": []string{"type"},
		},
		"AskAIHistoryEntry": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"run_id":                map[string]any{"type": "string", "format": "uuid"},
				"created_at":            map[string]any{"type": "string", "format": "date-time"},
				"status":                map[string]any{"type": "string", "enum": []string{"reserved", "success", "failure"}},
				"error_category":        map[string]any{"type": "string"},
				"provider":              map[string]any{"type": "string"},
				"model":                 map[string]any{"type": "string"},
				"template_version":      map[string]any{"type": "string"},
				"input_hash":            map[string]any{"type": "string", "description": "SHA-256 hash of the audit-safe request snapshot."},
				"output_hash":           map[string]any{"type": "string", "description": "SHA-256 hash of the validated Ask AI output."},
				"answer_chars":          map[string]any{"type": "integer"},
				"citation_count":        map[string]any{"type": "integer"},
				"chart_count":           map[string]any{"type": "integer"},
				"action_count":          map[string]any{"type": "integer"},
				"chart_types":           map[string]any{"type": "array", "items": map[string]any{"type": "string", "enum": []string{"line", "bar", "table"}}},
				"action_types":          map[string]any{"type": "array", "items": map[string]any{"type": "string", "enum": []string{"navigate", "download_export"}}},
				"input_tokens":          map[string]any{"type": "integer"},
				"output_tokens":         map[string]any{"type": "integer"},
				"total_tokens":          map[string]any{"type": "integer"},
				"tool_call_count":       map[string]any{"type": "integer"},
				"lifecycle_event_count": map[string]any{"type": "integer"},
				"tool_names":            map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
			},
			"required": []string{
				"run_id", "created_at", "status", "answer_chars", "citation_count", "chart_count", "action_count",
				"chart_types", "action_types", "input_tokens", "output_tokens", "total_tokens", "tool_call_count",
				"lifecycle_event_count", "tool_names",
			},
		},
		"AskAIHistoryResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"entries":  map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/AskAIHistoryEntry"}},
				"total":    map[string]any{"type": "integer"},
				"limit":    map[string]any{"type": "integer"},
				"offset":   map[string]any{"type": "integer"},
				"has_more": map[string]any{"type": "boolean"},
			},
			"required": []string{"entries", "total", "limit", "offset", "has_more"},
		},
		"UserBootstrap": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"session":     map[string]any{"$ref": "#/components/schemas/AuthSession"},
				"profile":     map[string]any{"$ref": "#/components/schemas/UserProfile"},
				"preferences": map[string]any{"$ref": "#/components/schemas/UserPreferences"},
				"teams":       map[string]any{"$ref": "#/components/schemas/TeamListResponse"},
				"permissions": map[string]any{"$ref": "#/components/schemas/PermissionContext"},
				"sites":       map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/Site"}},
				"status":      map[string]any{"$ref": "#/components/schemas/SystemStatus"},
			},
		},
		"OnboardingStep": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"key":         map[string]any{"type": "string", "enum": []string{"create_site", "verify_tracking", "automatic_events", "invite_teammate", "schedule_report"}},
				"complete":    map[string]any{"type": "boolean"},
				"current":     map[string]any{"type": "integer"},
				"target":      map[string]any{"type": "integer"},
				"site_id":     map[string]any{"type": "string", "format": "uuid"},
				"site_domain": map[string]any{"type": "string"},
			},
		},
		"UserOnboarding": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"dismissed": map[string]any{"type": "boolean"},
				"complete":  map[string]any{"type": "boolean"},
				"steps":     map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/OnboardingStep"}},
			},
		},
		"AuthSession": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"expires_at":                map[string]any{"type": "string", "format": "date-time"},
				"issued_at":                 map[string]any{"type": "string", "format": "date-time"},
				"duration_seconds":          map[string]any{"type": "integer"},
				"warning_seconds":           map[string]any{"type": "integer"},
				"extendable":                map[string]any{"type": "boolean"},
				"timing_adjustable":         map[string]any{"type": "boolean"},
				"remembered":                map[string]any{"type": "boolean"},
				"remember_expires_at":       map[string]any{"type": "string", "format": "date-time"},
				"remember_me_duration_days": map[string]any{"type": "integer"},
			},
		},
		"UserPasskey": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"id":         map[string]any{"type": "string", "format": "uuid"},
				"name":       map[string]any{"type": "string"},
				"created_at": map[string]any{"type": "string", "format": "date-time"},
				"updated_at": map[string]any{"type": "string", "format": "date-time"},
			},
		},
		"UserSecurityStatus": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"totp_enabled":             map[string]any{"type": "boolean"},
				"totp_pending":             map[string]any{"type": "boolean"},
				"passkeys":                 map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/UserPasskey"}},
				"recovery_codes_generated": map[string]any{"type": "boolean"},
				"recovery_codes_remaining": map[string]any{"type": "integer"},
				"password_login_enabled":   map[string]any{"type": "boolean"},
				"social_identities": map[string]any{
					"type": "array", "items": map[string]any{"$ref": "#/components/schemas/UserSocialIdentity"},
				},
			},
		},
		"UserSocialIdentity": map[string]any{
			"type":        "object",
			"description": "Safe linked-provider metadata. Immutable provider subjects are intentionally omitted.",
			"properties": map[string]any{
				"provider":       map[string]any{"type": "string", "enum": []string{"google", "github", "microsoft"}},
				"observed_email": map[string]any{"type": "string", "format": "email"},
				"linked_at":      map[string]any{"type": "string", "format": "date-time"},
				"last_used_at":   map[string]any{"type": "string", "format": "date-time"},
			},
			"required": []string{"provider", "linked_at"},
		},
		"UserRecoveryCodesResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"codes":     map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				"remaining": map[string]any{"type": "integer"},
			},
		},
		"UserTOTPSetup": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"secret":      map[string]any{"type": "string"},
				"otpauth_url": map[string]any{"type": "string"},
				"expires_at":  map[string]any{"type": "string", "format": "date-time"},
			},
		},
		"PermissionContext": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"instance_role": map[string]any{"type": "string"},
				"permissions": map[string]any{
					"type":                 "object",
					"additionalProperties": map[string]any{"type": "string"},
				},
				"instance_permissions":  map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				"instance_capabilities": map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				"site_capabilities": map[string]any{
					"type": "object",
					"additionalProperties": map[string]any{
						"type":  "array",
						"items": map[string]any{"type": "string"},
					},
				},
				"active_team_id":           map[string]any{"type": "string", "format": "uuid"},
				"active_team_role":         map[string]any{"type": "string"},
				"active_team_capabilities": map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				"can_create_teams":         map[string]any{"type": "boolean"},
			},
		},
		"APIClientSiteRole": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"site_id": map[string]any{"type": "string", "format": "uuid"},
				"role":    map[string]any{"type": "string"},
			},
		},
		"APIClient": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"id":            map[string]any{"type": "string", "format": "uuid"},
				"user_id":       map[string]any{"type": "string", "format": "uuid"},
				"tenant_id":     map[string]any{"type": "string", "format": "uuid"},
				"owner_type":    map[string]any{"type": "string", "enum": []string{"personal", "team"}},
				"name":          map[string]any{"type": "string"},
				"description":   map[string]any{"type": "string"},
				"instance_role": map[string]any{"type": "string"},
				"expires_at":    map[string]any{"type": "string", "format": "date-time"},
				"last_used_at":  map[string]any{"type": "string", "format": "date-time"},
				"revoked_at":    map[string]any{"type": "string", "format": "date-time"},
				"created_at":    map[string]any{"type": "string", "format": "date-time"},
				"updated_at":    map[string]any{"type": "string", "format": "date-time"},
				"site_roles":    map[string]any{"type": "array", "description": "Explicit site grants. Empty means the API client has no site-scoped analytics, MCP, or ingest access.", "items": map[string]any{"$ref": "#/components/schemas/APIClientSiteRole"}},
			},
		},
		"APIClientCreateResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"client": map[string]any{"$ref": "#/components/schemas/APIClient"},
				"token":  map[string]any{"type": "string"},
			},
		},
		"OpenAPIVersionList": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"latest": map[string]any{"type": "string"},
				"versions": map[string]any{
					"type": "array",
					"items": map[string]any{
						"type": "object",
						"properties": map[string]any{
							"version":     map[string]any{"type": "string"},
							"openapi_url": map[string]any{"type": "string"},
							"latest":      map[string]any{"type": "boolean"},
						},
					},
				},
			},
		},
		"ReportSchedule": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"frequency":   map[string]any{"type": "string", "enum": []string{"daily", "weekly", "monthly"}},
				"timezone":    map[string]any{"type": "string", "description": "IANA timezone name."},
				"local_time":  map[string]any{"type": "string", "pattern": "^([01][0-9]|2[0-3]):(00|15|30|45)$"},
				"weekly_day":  map[string]any{"type": "integer", "minimum": 0, "maximum": 6},
				"monthly_day": map[string]any{"type": "integer", "minimum": 1, "maximum": 28},
			},
			"required": []string{"frequency", "timezone", "local_time"},
		},
		"ReportDefinitionInput": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"name":                      map[string]any{"type": "string", "maxLength": 120},
				"scope":                     map[string]any{"type": "string", "enum": []string{"personal", "team"}},
				"tenant_id":                 map[string]any{"type": "string", "format": "uuid"},
				"preset":                    map[string]any{"type": "string", "enum": []string{"site_summary", "portfolio_digest", "opportunity_brief"}},
				"site_mode":                 map[string]any{"type": "string", "enum": []string{"selected", "all_accessible"}},
				"site_ids":                  map[string]any{"type": "array", "items": map[string]any{"type": "string", "format": "uuid"}},
				"recipient_user_ids":        map[string]any{"type": "array", "items": map[string]any{"type": "string", "format": "uuid"}},
				"external_recipient_emails": map[string]any{"type": "array", "maxItems": 25, "uniqueItems": true, "items": map[string]any{"type": "string", "format": "email"}},
				"schedule":                  map[string]any{"$ref": "#/components/schemas/ReportSchedule"},
				"status":                    map[string]any{"type": "string", "enum": []string{"draft", "active", "paused"}},
			},
			"required": []string{"name", "scope", "preset", "site_mode", "site_ids", "recipient_user_ids", "external_recipient_emails", "schedule", "status"},
		},
		"ReportDefinitionUpdate": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"name":                      map[string]any{"type": "string", "maxLength": 120},
				"preset":                    map[string]any{"type": "string", "enum": []string{"site_summary", "portfolio_digest", "opportunity_brief"}},
				"site_mode":                 map[string]any{"type": "string", "enum": []string{"selected", "all_accessible"}},
				"site_ids":                  map[string]any{"type": "array", "items": map[string]any{"type": "string", "format": "uuid"}},
				"recipient_user_ids":        map[string]any{"type": "array", "items": map[string]any{"type": "string", "format": "uuid"}},
				"external_recipient_emails": map[string]any{"type": "array", "maxItems": 25, "uniqueItems": true, "items": map[string]any{"type": "string", "format": "email"}},
				"schedule":                  map[string]any{"$ref": "#/components/schemas/ReportSchedule"},
				"status":                    map[string]any{"type": "string", "enum": []string{"draft", "active", "paused"}},
			},
		},
		"ReportDefinition": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"id":              map[string]any{"type": "string", "format": "uuid"},
				"tenant_id":       map[string]any{"type": "string", "format": "uuid"},
				"owner_user_id":   map[string]any{"type": "string", "format": "uuid"},
				"created_by":      map[string]any{"type": "string", "format": "uuid"},
				"name":            map[string]any{"type": "string"},
				"scope":           map[string]any{"type": "string", "enum": []string{"personal", "team"}},
				"preset":          map[string]any{"type": "string", "enum": []string{"site_summary", "portfolio_digest", "opportunity_brief"}},
				"site_mode":       map[string]any{"type": "string", "enum": []string{"selected", "all_accessible"}},
				"sites":           map[string]any{"type": "array", "items": map[string]any{"type": "object", "properties": map[string]any{"id": map[string]any{"type": "string", "format": "uuid"}, "domain": map[string]any{"type": "string"}}}},
				"recipients":      map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/ReportRecipient"}},
				"schedule":        map[string]any{"$ref": "#/components/schemas/ReportSchedule"},
				"status":          map[string]any{"type": "string", "enum": []string{"draft", "active", "paused"}},
				"consent_version": map[string]any{"type": "integer", "minimum": 1},
				"next_run_at":     map[string]any{"type": "string", "format": "date-time"},
				"last_outcome":    map[string]any{"type": "object", "additionalProperties": true},
				"created_at":      map[string]any{"type": "string", "format": "date-time"},
				"updated_at":      map[string]any{"type": "string", "format": "date-time"},
			},
			"required": []string{"id", "name", "scope", "preset", "site_mode", "sites", "recipients", "schedule", "status", "created_at", "updated_at"},
		},
		"ReportPreview": map[string]any{
			"type": "object", "properties": map[string]any{
				"subject": map[string]any{"type": "string"}, "preset": map[string]any{"type": "string"},
				"schedule":   map[string]any{"$ref": "#/components/schemas/ReportSchedule"},
				"site_count": map[string]any{"type": "integer"}, "recipient_count": map[string]any{"type": "integer"}, "pending_recipient_count": map[string]any{"type": "integer"},
				"period_start": map[string]any{"type": "string", "format": "date-time"}, "period_end": map[string]any{"type": "string", "format": "date-time"},
				"suppressed": map[string]any{"type": "boolean"},
			},
		},
		"ReportDelivery": map[string]any{
			"type": "object", "properties": map[string]any{
				"id": map[string]any{"type": "string", "format": "uuid"}, "recipient_id": map[string]any{"type": "string", "format": "uuid"}, "recipient_kind": map[string]any{"type": "string", "enum": []string{"member", "external"}}, "recipient_user_id": map[string]any{"type": "string", "format": "uuid"}, "recipient_email": map[string]any{"type": "string", "format": "email"},
				"status": map[string]any{"type": "string"}, "attempt_count": map[string]any{"type": "integer"},
				"next_attempt_at": map[string]any{"type": "string", "format": "date-time"}, "safe_error_code": map[string]any{"type": "string"},
				"smtp_accepted_at": map[string]any{"type": "string", "format": "date-time"},
			},
		},
		"ReportRecipient": map[string]any{
			"type": "object", "properties": map[string]any{
				"id": map[string]any{"type": "string", "format": "uuid"}, "kind": map[string]any{"type": "string", "enum": []string{"member", "external"}},
				"user_id": map[string]any{"type": "string", "format": "uuid"}, "email": map[string]any{"type": "string", "format": "email"},
				"status":       map[string]any{"type": "string", "enum": []string{"pending_confirmation", "confirmed", "opted_out"}},
				"confirmed_at": map[string]any{"type": "string", "format": "date-time"}, "confirmation_expires_at": map[string]any{"type": "string", "format": "date-time"},
				"invitation_state": map[string]any{"type": "string", "enum": []string{"pending", "sent", "failed"}}, "opted_out_at": map[string]any{"type": "string", "format": "date-time"},
			}, "required": []string{"id", "kind", "email", "status"},
		},
		"ReportRecipientConfirmation": map[string]any{
			"type": "object", "properties": map[string]any{
				"report_name": map[string]any{"type": "string"}, "team_name": map[string]any{"type": "string"}, "preset": map[string]any{"type": "string"},
				"schedule": map[string]any{"$ref": "#/components/schemas/ReportSchedule"}, "sites": map[string]any{"type": "array", "items": map[string]any{"type": "object", "properties": map[string]any{"id": map[string]any{"type": "string", "format": "uuid"}, "domain": map[string]any{"type": "string"}}}},
				"expires_at": map[string]any{"type": "string", "format": "date-time"},
			}, "required": []string{"report_name", "team_name", "preset", "schedule", "sites", "expires_at"},
		},
		"ReportRun": map[string]any{
			"type": "object", "properties": map[string]any{
				"id": map[string]any{"type": "string", "format": "uuid"}, "report_id": map[string]any{"type": "string", "format": "uuid"},
				"scheduled_for": map[string]any{"type": "string", "format": "date-time"}, "period_start": map[string]any{"type": "string", "format": "date-time"}, "period_end": map[string]any{"type": "string", "format": "date-time"},
				"status": map[string]any{"type": "string"}, "safe_error_code": map[string]any{"type": "string"},
				"deliveries": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/ReportDelivery"}},
			},
		},
		"ReportTestSendResponse": map[string]any{
			"type": "object", "properties": map[string]any{
				"status": map[string]any{"type": "string", "enum": []string{"accepted"}}, "message_id": map[string]any{"type": "string"}, "sent_at": map[string]any{"type": "string", "format": "date-time"},
			}, "required": []string{"status", "message_id", "sent_at"},
		},
		"LoginResponse": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"status":          map[string]any{"type": "string"},
				"challenge_token": map[string]any{"type": "string"},
				"factors":         map[string]any{"type": "array", "items": map[string]any{"type": "string", "enum": []string{"totp", "passkey", "recovery_code", "email_link"}}},
				"passkey":         map[string]any{"type": "object", "additionalProperties": true},
			},
		},
	}
}
