[build-system]
requires = ["hatchling", "setuptools", "wheel"]
build-backend = "hatchling.build"

[project]
name = "image-extractor"
dynamic = ["version"]
description = "This service will extract the images for each product from the CDN"
requires-python = ">=3.10"
license = "MIT"
keywords = ["Sentinel-2", "mosaicking"]
authors = [
    { name = "Parham Membari", email = "p.membari96@gmail.com" }
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]

dependencies = []  

[project.urls]
Documentation = "https://github.com/parham075/mouher-lab/image-extractor#readme"
Issues = "https://github.com/parham075/mouher-lab/issues"
Source = "https://github.com/parham075/mouher-lab/image-extractor"

[tool.hatch.version]
path = "src/image_extractor/__about__.py"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build]
packages = ["src/image_extractor"]




[project.scripts]
image-extractor = "image_extractor.main:main"

[tool.hatch.envs.default]
path = "envs/extractor"
dependencies = [
  "click==8.2.0",
  "numpy==2.2.5",
  "matplotlib==3.10.7",
  "rasterio==1.4.3",
  "loguru==0.7.3",
  "tqdm==4.67.1",
  "pandas==2.3.3",
]

[tool.hatch.envs.prod]
path = "/code/envs/extractor"
dependencies = [
  "click==8.2.0",
  "numpy==2.2.5",
  "matplotlib==3.10.7",
  "rasterio==1.4.3",
  "loguru==0.7.3",
  "tqdm==4.67.1",
  "pandas==2.3.3",
]

[tool.hatch.envs.tests]
path = "envs/tests"
dependencies = [
  "nose2==0.15.1",
  "click==8.2.0",
  "numpy==2.2.5",
  "matplotlib==3.10.7",
  "rasterio==1.4.3",
  "loguru==0.7.3",
  "tqdm==4.67.1",
  "pandas==2.3.3",
]
[tool.hatch.envs.prod.scripts]
mosaicking = "python -m image_extractor.main"

[[tool.hatch.envs.test.matrix]]
python = ["3.10"]

# Coverage settings
[tool.coverage.run]
source_pkgs = ["image_extractor"]
branch = true
parallel = true
omit = [
    "src/image_extractor/__about__.py",
]

[tool.coverage.paths]
image_extractor = ["src/image_extractor", "*/image_extractor/src/image_extractor"]


[tool.coverage.report]
exclude_lines = [
    "no cov",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
] 