apiVersion: v1
kind: ConfigMap
metadata:
  name: mouher-config
data:
  DJANGO_DEBUG: "0"
  DJANGO_ALLOWED_HOSTS: "api.mouher.example,mouher.example"
  MEDUSA_BACKEND_URL: "http://mouher-medusa-server:9000"
  MEDUSA_COUNTRY_CODE: "it"
  MEDUSA_CURRENCY_CODE: "eur"
  MEDUSA_REQUEST_TIMEOUT_SECONDS: "15"
  MOUHER_DEFAULT_PAYMENT_PROVIDER_ID: "pp_mouher-payment_mouher"
  MOUHER_WEB_PUSH_VAPID_SUBJECT: "mailto:owner@mouher.com"
  MEDUSA_WORKER_SERVER_MODE: "server"
  MEDUSA_WORKER_BACKGROUND_MODE: "worker"
  DISABLE_MEDUSA_ADMIN_IN_WORKER: "true"
  PAYMENT_SERVICE_URL: "http://mouher-payment-service:8080"
