apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mouher
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.example.yaml
  - storefront.yaml
  - commerce-api.yaml
  - medusa.yaml
  - payment-service.yaml
  - network-policy.yaml
  - pod-disruption-budgets.yaml
  - ingress.yaml
