apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mouher-payment-service-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mouher-payment-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: mouher-medusa-server
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: mouher-medusa-worker
      ports:
        - protocol: TCP
          port: 8080
