# Generated by Django 5.2.17 on 2026-09-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0003_catalog_snapshot"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="analyticsevent",
            new_name="commerce_an_event_n_78278a_idx",
            old_name="commerce_a_event_n_9575ef_idx",
        ),
        migrations.RenameIndex(
            model_name="analyticsevent",
            new_name="commerce_an_product_3ff70b_idx",
            old_name="commerce_a_product_7b6433_idx",
        ),
        migrations.RenameIndex(
            model_name="analyticsevent",
            new_name="commerce_an_country_93c623_idx",
            old_name="commerce_a_country_2ed897_idx",
        ),
        migrations.RenameIndex(
            model_name="analyticsevent",
            new_name="commerce_an_custome_20bf6f_idx",
            old_name="commerce_a_customer_1aac64_idx",
        ),
        migrations.RenameIndex(
            model_name="browserpushsubscription",
            new_name="commerce_br_custome_20ba50_idx",
            old_name="commerce_b_customer_1fbe91_idx",
        ),
    ]
