# Generated by Django 5.2.17 on 2026-09-15 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commerce",
            "0004_rename_commerce_a_event_n_9575ef_idx_commerce_an_event_n_78278a_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("invited", "Invited"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=80)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("success", "Success"),
                        ],
                        default="info",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "Unread"),
                            ("read", "Read"),
                            ("archived", "Archived"),
                        ],
                        default="unread",
                        max_length=16,
                    ),
                ),
                ("resource_type", models.CharField(blank=True, max_length=80)),
                ("resource_id", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="commerce_ad_status_2b7eba_idx",
                    ),
                    models.Index(
                        fields=["type", "severity"], name="commerce_ad_type_3a7d52_idx"
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="commerce_ad_resourc_e98545_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DashboardDailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("visitors", models.PositiveIntegerField(default=0)),
                ("product_views", models.PositiveIntegerField(default=0)),
                ("add_to_cart_count", models.PositiveIntegerField(default=0)),
                ("checkout_count", models.PositiveIntegerField(default=0)),
                ("purchase_count", models.PositiveIntegerField(default=0)),
                ("order_count", models.PositiveIntegerField(default=0)),
                (
                    "gross_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "net_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("currency", models.CharField(default="EUR", max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="commerce_da_date_e3c513_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="OwnerRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("permissions", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="commerce_ow_name_f7d0c8_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="OwnerUserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commerce.ownerrole",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commerce.owneruser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="owneruser",
            name="roles",
            field=models.ManyToManyField(
                related_name="users",
                through="commerce.OwnerUserRole",
                to="commerce.ownerrole",
            ),
        ),
        migrations.CreateModel(
            name="ProductAdminNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=128)),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_notes",
                        to="commerce.owneruser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(blank=True, max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_support_tickets",
                        to="commerce.owneruser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportTicketMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("owner", "Owner"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("author_id", models.CharField(blank=True, max_length=160)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="commerce.supportticket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=128)),
                ("resource_type", models.CharField(max_length=80)),
                ("resource_id", models.CharField(blank=True, max_length=160)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="commerce.owneruser",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="commerce_ad_action_eca6e6_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="commerce_ad_resourc_9e429d_idx",
                    ),
                    models.Index(
                        fields=["owner_user", "created_at"],
                        name="commerce_ad_owner_u_84dd1e_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="owneruserrole",
            constraint=models.UniqueConstraint(
                fields=("owner_user", "owner_role"), name="unique_owner_user_role"
            ),
        ),
        migrations.AddIndex(
            model_name="owneruser",
            index=models.Index(fields=["email"], name="commerce_ow_email_413716_idx"),
        ),
        migrations.AddIndex(
            model_name="owneruser",
            index=models.Index(fields=["status"], name="commerce_ow_status_2700c1_idx"),
        ),
        migrations.AddIndex(
            model_name="productadminnote",
            index=models.Index(
                fields=["product_id", "created_at"],
                name="commerce_pr_product_417af1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productadminnote",
            index=models.Index(
                fields=["owner_user", "created_at"],
                name="commerce_pr_owner_u_9989f5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["status", "priority"], name="commerce_su_status_b4a354_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["customer_id"], name="commerce_su_custome_a8a4ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["assigned_owner", "status"],
                name="commerce_su_assigne_dfc3e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["created_at"], name="commerce_su_created_f0c0bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticketmessage",
            index=models.Index(
                fields=["ticket", "created_at"], name="commerce_su_ticket__04a4d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticketmessage",
            index=models.Index(
                fields=["author_type", "author_id"],
                name="commerce_su_author__a544d6_idx",
            ),
        ),
    ]
